w4d3/config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end
  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create]

  root to: redirect("/cats")
end

w4d3/app/models/user.rb
class User < ActiveRecord::Base
  validates :user_name, :password_digest, :session_token, presence:true
  validates :user_name, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password, :email

  after_initialize :ensure_session_token

  has_many :cats

  def email=(email)
    @email = email
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    bc_obj = BCrypt::Password.new(self.password_digest)
    bc_obj.is_password?(password)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
end

w4d3/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :validate_current_user, only: :new

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.valid?
      msg = UserMailer.welcome_email(@user)
      msg.deliver

      login!(@user)
      @user.save
      redirect_to cats_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password, :email)
  end
end

w4d3/app/views/users/new.html.erb
<p>
  Welcome to the cool cats club! Please enter your details below
</p>

<form action='<%= users_url %>' method='post'>
  <%= auth_token %>
  <label>
    <input type='text' name='user[user_name]' placeholder="Enter username">
  </label>

  <label>
    <input type='password' name='user[password]' placeholder="Enter password">
  </label>

  <label>
    <input type='text' name='user[email]' placeholder='Enter email'>
  </label>
  <input type='submit'>
</form>


<% content_for :footer do %>
  <p>Hello from the sign up page</p>
<% end %>